#ifndef PRINTF_CONFIG_H_
#define PRINTF_CONFIG_H_

#define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 0
#define PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS 0
#define PRINTF_SUPPORT_WRITEBACK_SPECIFIER 1
#define PRINTF_SUPPORT_MSVC_STYLE_INTEGER_SPECIFIERS 1
#define PRINTF_SUPPORT_LONG_LONG 1
#define PRINTF_USE_DOUBLE_INTERNALLY 0
#define PRINTF_ALIAS_STANDARD_FUNCTION_NAMES_SOFT 1
#define PRINTF_ALIAS_STANDARD_FUNCTION_NAMES_HARD 0

#endif  // PRINTF_CONFIG_H_
